### ISSUE TITLE
Browser - Unable to expand Sub-Collections in ToC

### ISSUE THREAD

**Issue by dak** [Connexions/webview#1257]
![image](https://cloud.githubusercontent.com/assets/1371232/11479080/1d9e56a2-975e-11e5-8391-7c5c40c36dc2.png)

**Comment by edwoodward** [comment]
If you are testing on dev, the code has not been updated. Where are you 
testing?

**Comment by dak** [comment]
@edwoodward On my local, updated install

**Comment by RoyEJohnson** [comment]
If you're not seeing chapter numbers by the page title, you may have cache issues. The master branch should give you this when you load the Biology book and open the Contents window (the current section is automatically expanded, and you start on the Introduction rather than the Preface).

![screen shot 2015-11-30 at 1 00 01 pm](https://cloud.githubusercontent.com/assets/7315241/11481323/622baa64-9762-11e5-80ad-d90aebaef7bf.png)

**Comment by dak** [comment]
Fixed in latest build
