### ISSUE TITLE
Lines on Example boxes not consistent

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/webview#1639]
@Stackblocks commented on [Tue May 08 2018](https://github.com/Connexions/cnx-recipes/issues/393)

![example double lines](https://user-images.githubusercontent.com/33228728/39324728-d0a914d4-4955-11e8-8518-20ad5bc15708.jpg)

---

@lwtchu commented on [Fri Jun 01 2018](https://github.com/Connexions/cnx-recipes/issues/393#issuecomment-393906541)

@Stackblocks this might be due to the fact that there's an exercise embedded in the example. the second line is for the exercise

**Comment by Adrianltd** [comment]
I thought that I have already commented on this. Some of those are `exercise` tags inside `example` tags and some are not so I guess it's a recipe issue. Am I wrong? @helenemccarron

**Comment by helenemccarron** [comment]
This might be a caching issue, this is how it displays for me now.
![2018-07-05_11-02-07](https://user-images.githubusercontent.com/8514591/42334470-eb142ede-8042-11e8-986e-22eedf27be5e.png)

**Comment by wilkus27** [comment]
The first question is, on which server was this issue found? On devb, sign "Example" is on the gray background and on cnx.org there is no numbering of example, but on the screenshot from Alan "Example" is on the black background.

Next question: what is the issue about? The problem is that there are two lines in Example 3.2 (red arrows) or that there is different padding between left side of the example box and beginnig of the text in both of the examples (blue arrows).

![lines2](https://user-images.githubusercontent.com/40228854/42367301-05be41c2-8104-11e8-99ee-8f39d9448d57.png)

**Comment by helenemccarron** [comment]
@wilkus27 my screenshot was taken from devb, there is no baked content on dev.cnx.org. In other words, I do not see the issue when the book is baked.

**Comment by openstaxalina** [comment]
@Stackblocks will verify that the book is baked and that this is no longer an issue.

**Comment by Stackblocks** [comment]
I agree that the examples in the original post look unbaked. Attached are images of how the examples look both collapsed and expanded. Note the lightness of the line above show solution, that is pretty consistent across baked content.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/d4bb4d0a-a0a2-44bc-9440-36fbdf1cb1b1)
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/7554c94b-5958-4d2d-a7ba-9c2ed81ee257)
