### ISSUE TITLE
Table title/caption font are same size as body text

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/webview#1640]
@Stackblocks commented on [Tue May 08 2018](https://github.com/Connexions/cnx-recipes/issues/394)

<img width="445" alt="screen shot 2018-04-26 at 12 07 00 pm" src="https://user-images.githubusercontent.com/1895432/39320661-6c3421e8-494a-11e8-9c96-4bfbafa419bb.png">

**Comment by Adrianltd** [comment]
So the gap between table and caption is caused by empty `<caption></caption>` inserted after every table in baking process. There's already an [issue](https://github.com/Connexions/cnx-recipes/issues/434) for that.

And about the font: I've added 0.9em font-size to the .os-caption-container, but first of all, as mentioned above - there is `caption` tag generated during baking process, it should contain the table title. And then, do we have any font convention or is using em/rem 0.1 lower ok? Anyway, we should create some general styleguide, so the fonts, paddings, margins and all others are consistent.

**Comment by helenemccarron** [comment]
@Stackblocks this is related to https://github.com/Connexions/cnx-recipes/issues/434 - can we move this to recipes

**Comment by wilkus27** [comment]
Verified on devb: 

![font_table](https://user-images.githubusercontent.com/40228854/42368582-b1a36afa-8107-11e8-9519-188150cbb4a4.png)
