### ISSUE TITLE
Intro to Business: Terms and Index Terms are Bolded

### ISSUE THREAD

**Issue by Bkblodget** [Connexions/webview#1704]
both <term> and <glossary> items appear as bolded text in webview. Only <glossary> terms should appear in bolded text, as in the PDF.

I believe this happens because webview lacks an Index.

**Comment by openstaxalina** [comment]
This is most likely happening for all titles.

**Comment by openstaxalina** [comment]
@Bkblodget will provide any known examples for testing purposes.  These changes will apply to all books.

**Comment by brittany-johnson** [comment]
University Physics V 3 Key Terms section on production
![screen shot 2018-07-10 at 10 14 01 am](https://user-images.githubusercontent.com/24909007/42519696-39e22c2e-842a-11e8-8239-5c317a4f4e8f.png)

Intro to Business Key Terms Section on devb
![screen shot 2018-07-10 at 10 14 10 am](https://user-images.githubusercontent.com/24909007/42519697-39f58d3c-842a-11e8-8472-1bfebd21019e.png)

Index U Physics 
<img width="1373" alt="screen shot 2018-07-10 at 10 15 34 am" src="https://user-images.githubusercontent.com/24909007/42519704-3d3801f0-842a-11e8-8964-92a4dd037e0e.png">

Index Intro business 
<img width="1345" alt="screen shot 2018-07-10 at 10 15 24 am" src="https://user-images.githubusercontent.com/24909007/42519705-3d51f0f6-842a-11e8-90bc-a4bdf5f903e7.png">


The key terms in intro business appear to be displaying correctly, and it has an index. I used UPhysics as another example that's on production since the syles are universal. Since this issue was created a day ago, something weird may be going on if youre not able to see this. 

 [Intro business on dev b](https://devb.cnx.org/contents/Mmq0W-88@12.1:SBfkOk9C@12.1/Key-Terms)

Let me know if you're still not seeing what is in the screenshots! @Bkblodget cc: @Stackblocks

**Comment by Bkblodget** [comment]
@brittany-johnson sorry for the lack of clarification - this issue actually refers to terms that are in the body portion of the content. For instance, in the screenshot below **Walmart** is a term tag and should not appear bolded. 

![screen shot 2018-07-10 at 10 28 23 am](https://user-images.githubusercontent.com/11299035/42520560-2a02ae08-842c-11e8-8be4-b0295c9505ea.png)

**Comment by brittany-johnson** [comment]
@Bkblodget AHHH! Makes sense now, thank you!

**Comment by brittany-johnson** [comment]
One more thing, can you post the link from the screenshot? Thanks! @Bkblodget

**Comment by helenemccarron** [comment]
As a side note, I do not think the content shown in the screenshot is present on devb. Should we consider moving it over so we can test?

**Comment by Stackblocks** [comment]
I think these can be found at https://devb.cnx.org/contents/qAil3UeG@2.1:MJPTog5b@2/38-Threats-and-Opportunities-i

**Comment by helenemccarron** [comment]
@brittany-johnson it looks like we need to make sure the class `no-emphasis` is honored on webview.

**Comment by brittany-johnson** [comment]
Update from PL on Friday July 13th scrum: this change will only affect the currently baked books

**Comment by openstaxalina** [comment]
@Bkblodget Alan pointed out above that chapters 3, 9, and 18 intro modules are numbered "3.1," "9.1", "18.1" when they shouldn't be.  I bet this is due to them missing the "intro" or "introduction" class (I can't remember which it is).  Could you check w/ SRM on this and ensure they are using the class?

**Comment by brittany-johnson** [comment]
![screen shot 2018-07-17 at 9 16 33 am](https://user-images.githubusercontent.com/24909007/42823073-3d83bcc6-89a2-11e8-9541-eb91557a055a.png)
Terms with the class `.no-emphasis` are now displaying with a normal font weight. This can be tested by inspecting index terms, which should have a class `.no-emphasis` and be unbolded.

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/da2218e0-8f34-4770-b468-4d1d5c48aff9)

---

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/e162f8a5-de15-49fc-b31a-54366dc0e473)
