### ISSUE TITLE
Different alignment of sentences in table

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#1810]
The sentences in table are differently aligned. In the first column - to the center and in the second one - aligned up.
https://katalyst01.cnx.org/contents/jQSmhtXo@16.36:0liD6Cpr@3/152-The-First-Law-of-Thermodyn

![table_align](https://user-images.githubusercontent.com/40228854/43777060-00bbfc66-9a52-11e8-873e-4b1e4b87d5dc.JPG)

This is how it looks in pdf:

![table_align_pdf](https://user-images.githubusercontent.com/40228854/43777090-157adf32-9a52-11e8-8fa5-0186ed1ed649.JPG)

**Comment by PiotrKozlowski** [comment]
This is happening because again `mathml` is set to be displayed as a block. We can change it in CNXML (see https://github.com/Connexions/webview/issues/1789#issuecomment-411155980) or we can force MathJax to display inline inside tables - this will apply to all baked tables.
![issue](https://user-images.githubusercontent.com/31478212/43820382-673d9ec4-9ae6-11e8-9097-a2ce2f42cd6e.png)

**Comment by openstaxalina** [comment]
okay, moving this issue to the content-managers repo. cc @PiotrKozlowski

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/content-managers #215](https://github.com/Connexions/content-managers/issues/215) via [**ZenHub**](https://www.zenhub.com/)
