### ISSUE TITLE
Equations are not displayed correctly when zoomed out (Safari)

### ISSUE THREAD

**Issue by uskka** [Connexions/webview#1827]
Description: When screen is zoomed out once, few equations are not displayed correctly. Tested on MacBook 13,3" , Safari. Issue doesn't appear on Chrome. 

https://katalyst01.cnx.org/contents/vEmOH-_p@4.48:EpNx8345@4/51-Price-Elasticity-of-Demand-

![image-4](https://user-images.githubusercontent.com/40228918/44043435-28b94c8e-9f23-11e8-9fb7-63e55fe6656c.png)

![image](https://user-images.githubusercontent.com/40228918/44043217-8f02d9ac-9f22-11e8-8b37-6b5b9698e0a4.png)

**Comment by PiotrKozlowski** [comment]
@openstaxalina you are correct. Probably browsers is overriding MathJax fonts settings when zooming out for some reason. 

MathJax display equations in "hard" content-box which width / height depends on font-size and we really do not want to override it again because impact will be globally.

What should we do with this issue?

**Comment by openstaxalina** [comment]
Thank you @PiotrKozlowski - due to the benefit vs cost analysis captured above, I am going to close this issue.
