### ISSUE TITLE
Special character in not displayed inline on webview

### ISSUE THREAD

**Issue by openstaxalina** [Connexions/webview#1889]
@uskka commented on [Thu Aug 30 2018](https://github.com/Connexions/content-managers/issues/279)

X should be displayed inline. 

https://katalyst01.cnx.org/contents/tWu56V64@34.15:V_Scj1km@34.15/Key-Terms

**Webview**

![screenshot-katalyst01 cnx org-2018 08 29-15-21-14](https://user-images.githubusercontent.com/40228918/44844600-a96fc800-ac4b-11e8-96e7-1e28b85db5b5.png)
**PDF**

![a](https://user-images.githubusercontent.com/40228918/44844709-f5227180-ac4b-11e8-8bae-8c26865ab1a1.png)

**Comment by openstaxalina** [comment]
This issue is a copy of https://github.com/Connexions/content-managers/issues/279.  Need to decide if this is code or content.

**Comment by PatBoj** [comment]
@openstaxalina It's a content issue, because in the raw html file ![image](https://user-images.githubusercontent.com/20907906/44973669-a2073200-af5d-11e8-9876-07be7d62befb.png) has `display` set as `block`.

![image](https://user-images.githubusercontent.com/20907906/44973780-f9a59d80-af5d-11e8-9b8a-1d8800534d7d.png)
![image](https://user-images.githubusercontent.com/20907906/44973785-fb6f6100-af5d-11e8-98f9-d5f1e3b8c1d4.png)

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/content-managers #287](https://github.com/Connexions/content-managers/issues/287) via [**ZenHub**](https://www.zenhub.com/)
