### ISSUE TITLE
Presentation math displaying inline in webview

### ISSUE THREAD

**Issue by openstaxalina** [Connexions/webview#1912]
Webview on the left; PDF on the right.
![presentationvsinline](https://user-images.githubusercontent.com/7863733/45115913-e25de000-b116-11e8-8c79-90588c34179d.png)

Content on staging: https://staging.cnx.org/contents/vEmOH-_p@5.1:RnWi-sXU@3/17-3-How-to-Accumulate-Personal-Wealth

I think this is likely a content issue but would like @PatBoj @Adrianltd or @PiotrKozlowski to confirm if possible.

**Comment by PiotrKozlowski** [comment]
Those equations are plain text instead of mathml: 
`<div data-type="equation" id="eip-671">$100 × 0.05 × 3 = $15</div>`

We can set `text-align: center;` for `data-type="equation"` inside `.os-note-body` but this can cause regression.

Other solution is to create those equation with mathml and display them as a block.

@openstaxalina

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/content-managers #298](https://github.com/Connexions/content-managers/issues/298) via [**ZenHub**](https://www.zenhub.com/)
