### ISSUE TITLE
Numbered Equations styled incorrectly in webview for College Physics

### ISSUE THREAD

**Issue by oscryan** [Connexions/webview#1924]
PDF on the right, staging webview on the left:
<img width="1270" alt="screen shot 2018-09-06 at 2 58 23 pm" src="https://user-images.githubusercontent.com/1895432/45181956-8b730c00-b1e5-11e8-8cb0-1a83cb54471b.png">

**Comment by openstaxalina** [comment]
Link to content in screenshot: https://staging.cnx.org/contents/Ax2o07Ul@14.1:cPzgoAtX@5/21-2-Electromotive-Force-Terminal-Voltage#42247

Note that the number is in the wrong place for all numbered equations in College Physics.  This may be a cnx-recipes issue since we've only logged this for the one title.

**Comment by PiotrKozlowski** [comment]
Those numbers looks like `<span class="os-number">21.47</span>` but should look like:
```
<div class="os-equation-number">
   <span class="os-number">21.47</span>
   <span class="os-divider"> </span>
</div>
```
So this is recipes related.

**Comment by Adrianltd** [comment]
Issue moved to [Connexions/cnx-recipes #609](https://github.com/Connexions/cnx-recipes/issues/609) via [**ZenHub**](https://www.zenhub.com/)
