### ISSUE TITLE
KNOWN ISSUE: Blank spaces in headers of tables

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#1976]
On katalyst01 (https://katalyst01.cnx.org/contents/LnN76Opl@14.4:ySOb2aRL@3/7-1-Overview-of-Our-Planetary-System) in some tables there is too long distance between words in headers of columns.

![distance](https://user-images.githubusercontent.com/40228854/46816031-67728f80-cd7c-11e8-8426-afd4c682efac.JPG)

Other places:
1) https://katalyst01.cnx.org/contents/LnN76Opl@14.4:FfqQvtot@4/1-8-The-Universe-of-the-Very-Small **Table 1.1**
2) https://katalyst01.cnx.org/contents/LnN76Opl@14.4:E5Z0utOB@3/11-2-The-Giant-Planets **Table 11.3**

This issue is probably related with https://github.com/Connexions/content-managers/issues/199

**Comment by lwtchu** [comment]
Super low priority: petition to treat as a known issue and close.

**Comment by openstaxalina** [comment]
Per @Bkblodget:
The <newline> spacing was purposely implemented to reduce the size of the tables for printing. I do not think we should alter the markup and come across this problem again when it is time for print.

I believe this is a problem with the way webview handles newlines: it adds a lot of space.

I agree that we should treat as a low-priority known issue; however, I recommend we eventually fix this in code rather than content.

**Comment by lwtchu** [comment]
Issue moved to [Connexions/content-managers #431](https://github.com/Connexions/content-managers/issues/431) via [**ZenHub**](https://www.zenhub.com/)
