### ISSUE TITLE
Paragraph out of padding

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#1980]
On katalyst01 (https://katalyst01.cnx.org/contents/LnN76Opl@14.4:Ip54klHK@14.4/Exercises) there is one paragraph out of padding:

![p_out](https://user-images.githubusercontent.com/40228854/47009822-b7b36e00-d13d-11e8-8655-2febe4a07144.JPG)

**Comment by oscryan** [comment]
This may be be as desired; the header is also left-aligned, and this is a paragraph of instructions within a collating exercise section.

**Comment by openstaxalina** [comment]
Agree w/ @oscryan that this is acceptable as is.

It doesn't look exactly like the PDF:
![screen shot 2018-10-16 at 3 31 09 pm](https://user-images.githubusercontent.com/7863733/47045506-9744dd00-d158-11e8-9216-7c4e77e74d3d.png)

...but it is an equally acceptable display, since the instructions pertain to multiple exercises following:
![screen shot 2018-10-16 at 3 31 01 pm](https://user-images.githubusercontent.com/7863733/47045567-bc395000-d158-11e8-81b4-5d36f0934ed2.png)

**Comment by openstaxalina** [comment]
Also, the text wrapping is different between PDF and webview, and that also makes this content's left-alignment better in webview.
