### ISSUE TITLE
Too small figures in tables

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#2032]
On katalyst01 (https://katalyst01.cnx.org/contents/CImQfPDv@3.14:Tj87ETCR@4/3-1-Use-a-Problem-Solving-Strategy) some figures in tables are soo small that it's impossible to read them.

![figures](https://user-images.githubusercontent.com/40228854/47914266-3f6bdd00-de9f-11e8-9226-dd75c13a1f23.JPG)

**Comment by lwtchu** [comment]
@wilkus27 is it possible to tell if the CSS is resizing the images? They weren't created to be that small.

**Comment by PiotrKozlowski** [comment]
@lwtchu This table doesn't have headers `<thead><th>...` so width of cells depends of their content and one of the cells (Step 6.) from left side have a lot of content and this is why there is so little space for images.

Possible solutions:
**In the content:**
1. Add headers to this table in the content and give every column same amount of space.
2. Add to this table in the content `table-layout: fixed;` - This will set equal width (50%) for each column, however I don't know if you can add this in the content.
**In the css:**
3. Add `table-layout: fixed;` for every table - probably the worst solution, because all cells in all tables will have same width.
**In javascript:**
4. Detect if table have images and if so then set cell width to image width - this probably require some additional testing

**Comment by openstaxalina** [comment]
@PiotrKozlowski I think the javascript solution would be best, since this applies to multiple tables.  

If javascript doesn't work, we can do the content solution.  

I agree that the css solution is not feasible.

cc @helenemccarron

**Comment by openstaxalina** [comment]
After discussion in sprint planning, we do **not** want to pursue the javascript or css solutions.

We will pursue adding a class such as "has-images" on the table and setting column widths for those tables to share the viewport equally.

**Comment by openstaxalina** [comment]
(The best solution would be to have colored math so that we do not have to have these images in the tables.)

**Comment by lwtchu** [comment]
@PiotrKozlowski i added a `has-images` class to the table to see if we can set some fixed widths for tables with images that are too small

**Comment by PiotrKozlowski** [comment]
Merged into master

**Comment by wilkus27** [comment]
Verified on katalyst01

![small_fig](https://user-images.githubusercontent.com/40228854/48774667-2e0e3780-eccb-11e8-8e45-ca120e0b4866.JPG)
