### ISSUE TITLE
Image sizing inappropriate in chem 2e answer key on staging

### ISSUE THREAD

**Issue by oscryan** [Connexions/webview#2098]
https://staging.cnx.org/contents/f8zJz5tx@4.2:oNj8Zbuz@4.2/Answer-Key

webview on the left; PDF on the right 

<img width="1378" alt="screen shot 2018-11-28 at 5 35 05 pm" src="https://user-images.githubusercontent.com/1895432/49234656-17986800-f3be-11e8-934c-0c6501982058.png">
<img width="1397" alt="screen shot 2018-11-28 at 5 34 28 pm" src="https://user-images.githubusercontent.com/1895432/49234657-17986800-f3be-11e8-82f6-1149d9e4153a.png">

**Comment by Adrianltd** [comment]
I believe this might be tricky. There's already a `span` container with class `scaled-down` for images. It is set to be `width: 60%`. So some of the images are already being scaled down. By changing this to other value, we might create a regression in other places (I'm not aware of where else this class is being used).
I would use `object-fit: scale-down` for the images, so if the image was bigger than the container it would be scaled down to fit the container while keeping the aspect ratio and if the image was smaller than the container, it would do nothing. 
But there's a catch - old browsers might not support that yet (IE has no support yet, Edge has support for images only which is fine, other browsers should work. Unless they weren't updated since 3 years or more).
https://caniuse.com/#search=object-fit

What do you think @helenemccarron @PiotrKozlowski @openstaxalina ?

**Comment by Adrianltd** [comment]
Also I have noticed, that this doesn't occur in regular `Chemistry` book. That's due to absence of `scaled-down` class there.

**Comment by openstaxalina** [comment]
*Decision:* we need to remove the `scaled-down` class from images **_in the answer key only_** in chemistry.

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/content-managers #491](https://github.com/Connexions/content-managers/issues/491) via [**ZenHub**](https://www.zenhub.com/)
