### ISSUE TITLE
Book Editor - New collection should open with TOC open

### ISSUE THREAD

**Issue by edwoodward** [Connexions/webview#870]
Users are reporting that they cannot find the Add button on a new Book.  We should open a new Book with the TOC open so the Add button is easier to find.

**Comment by reedstrm** [comment]
I bet we get report a about it being hard to find the book you just created in the workspace, too. (eventually) Could kill both those by redirecting after the create-new popup title modal to the ContentView of the book. We can't just always open books w/ the TOC open, because of the "page is below the fold" problem for any book of reasonable length.
