### ISSUE TITLE
Editor - Text duplicated if last thing after an image

### ISSUE THREAD

**Issue by edwoodward** [Connexions/webview#910]
I was able to recreate this twice.  I added an image to a Page and published.  I then went back to edit it and added some text such as "This is a test", saved and publshed.  When I viewed the Page, the text after the image was 

`This is a testThis is a testThis is a testThis is a testThis is a testThis is a testThis is a testThis is a testThis is a testThis is a testThis is a testThis is a testThis is a testThis is a testThis is a testThis is a test`

I then editing the Page again and changed the text after the image to "Different text test" and republished.  The text in the published version was 

`Different text testDifferent text testDifferent text testDifferent text testDifferent text testDifferent text testDifferent text testDifferent text testDifferent text testDifferent text testDifferent text testDifferent text testDifferent text testDifferent text testDifferent text testDifferent text test`

This is on dev: http://dev.cnx.org/contents/f449c585-e758-455a-bc49-6a6c17aa1101/Test_1-12

I'm not sure if this is an editor issue or something about how the data is being passed to Authoring.

**Comment by dak** [comment]
@edwoodward I wasn't able to duplicate this issue editing a page in a book.  Still trying other combinations.  However, webview is only sending the ID to be published (and commit log message) to authoring, so if the page is loading correctly when editing/saving, then it would seem to be an issue with publishing.

@pumazi @karenc @reedstrm Thoughts on what could be causing this?

**Comment by edwoodward** [comment]
I've seen this error several times and have not been able to duplicate 
it.  However today I was able to.

**Comment by pumazi** [comment]
@edwoodward I'd suggest you look at the json each POST and GET.

@dak Authoring and the other sever-side components aren't doing anything out of the ordinary with the content. I'm not sure how duplication would happen

**Comment by pumazi** [comment]
This could be similar to what I was observing in #775.

**Comment by dak** [comment]
@pumazi I don't think it's related since #775 was very specifically appending `p` tags, not duplicating anything.

I haven't been able to duplicate this exact issue yet, although I have noticed that content gets rather muddled at some point (it seemed to happen after publish, although I'm not 100% sure on that).

Below is something I recently test published and you can see it became littered with XML Namespace data.  The `add figure` left and right spans shouldn't exist either, which may be an issue with aloha.

```html
<p xmlns="http://www.w3.org/1999/xhtml" xmlns:bib="http://bibtexml.sf.net/" xmlns:data="http://dev.w3.org/html5/spec/#custom" xmlns:epub="http://www.idpf.org/2007/ops" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:lrmi="http://lrmi.net/the-specification">test text</p><p xmlns="http://www.w3.org/1999/xhtml" xmlns:bib="http://bibtexml.sf.net/" xmlns:data="http://dev.w3.org/html5/spec/#custom" xmlns:epub="http://www.idpf.org/2007/ops" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:lrmi="http://lrmi.net/the-specification"></p><figure xmlns="http://www.w3.org/1999/xhtml" xmlns:bib="http://bibtexml.sf.net/" xmlns:data="http://dev.w3.org/html5/spec/#custom" xmlns:epub="http://www.idpf.org/2007/ops" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:lrmi="http://lrmi.net/the-specification"><span class="add-figure-left">+</span><div class="title" id="345ba0c0-a0e7-797b-011e-d05062ae3413"></div><img src="http://www.nerdist.com/wp-content/uploads/2014/11/game-of-thrones-iron-throne.jpg" alt="throne" draggable="false"/><figcaption><p id="ad5066b3-4298-4991-54a0-30fd51febc9e"></p></figcaption><span class="add-figure-right">+</span></figure><p xmlns="http://www.w3.org/1999/xhtml" xmlns:bib="http://bibtexml.sf.net/" xmlns:data="http://dev.w3.org/html5/spec/#custom" xmlns:epub="http://www.idpf.org/2007/ops" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:lrmi="http://lrmi.net/the-specification"><br/></p><p xmlns="http://www.w3.org/1999/xhtml" xmlns:bib="http://bibtexml.sf.net/" xmlns:data="http://dev.w3.org/html5/spec/#custom" xmlns:epub="http://www.idpf.org/2007/ops" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:lrmi="http://lrmi.net/the-specification">more test text</p><p xmlns="http://www.w3.org/1999/xhtml" xmlns:bib="http://bibtexml.sf.net/" xmlns:data="http://dev.w3.org/html5/spec/#custom" xmlns:epub="http://www.idpf.org/2007/ops" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:lrmi="http://lrmi.net/the-specification">testtext2</p><p xmlns="http://www.w3.org/1999/xhtml" xmlns:bib="http://bibtexml.sf.net/" xmlns:data="http://dev.w3.org/html5/spec/#custom" xmlns:epub="http://www.idpf.org/2007/ops" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:lrmi="http://lrmi.net/the-specification"><br/></p><p xmlns="http://www.w3.org/1999/xhtml" xmlns:bib="http://bibtexml.sf.net/" xmlns:data="http://dev.w3.org/html5/spec/#custom" xmlns:epub="http://www.idpf.org/2007/ops" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:lrmi="http://lrmi.net/the-specification"></p>
```

**Comment by pumazi** [comment]
I do know we have a bit of a namespace problem in cnx-epub, but they don't seem to affect anything, as you have pointed out later in your post.

We definitely need a more reproducible action set. Very little can be derived from this case at this point. I'll try to reproduce this as soon as possible.

**Comment by edwoodward** [comment]
I have been able to reliably duplicate the bug on beta.cnx.org.  The text is duplicated if it is the last part of a Page and does not have a line break after the text.  I edited and published the same page multiple times and each time, the text was duplicated on publish until I put a line break after the text. If I edited the Page, returned to my Workspace and reopened the Page, the text was not duplicated.  This looks like it is happening in Authoring, epub or publishing and not in the editor..

**Comment by dak** [comment]
We need to make sure fixing this doesn't cause the regression https://github.com/Connexions/webview/pull/818 was made to fix.

**Comment by pumazi** [comment]
It could be happening in cnx-epub. I thought it was doing a straight injection of the content into the html template. It appears that the content is being rolled over with an xpath to exclude various metadata elements from the content. I'll need to look closer to make sure.

**Comment by amberwebb** [comment]
@pumazi @edwoodward @dak I am able to reproduce this issue on a new page. When I inserted a line break after the image, the problem was resolved. I also derived Ed's content in question and my new text came out as expected.

**Comment by pumazi** [comment]
@rich-hart Try looking for the problem in cnx-epub at https://github.com/Connexions/cnx-epub/blob/a7221261566aa41b5cea557bd109e47fc54d54d2/cnxepub/models.py#L374

**Comment by rich-hart** [comment]
So I think I have tracked down where the issue is coming from.  It looks like the editor is having trouble parsing images contained within the paragraph tags.  If you have a text string in the editor. 


![original_text](https://cloud.githubusercontent.com/assets/2857670/6694508/c0561118-cca8-11e4-97a2-ebf9e5dcf68a.png)

It is contained within the standard paragraph tag: 
``` html
<p> Enter some content here. Format content, and drag and drop elements from the toolbar. </p>
```

When you add in an image inside of the paragraph tag itself...

![text_duplication](https://cloud.githubusercontent.com/assets/2857670/6694442/613421e8-cca8-11e4-979d-971a0c15dac1.png)

You end up with this following html code: 
``` html 
<p> Enter some content here. Format content,
	<div class= "semantic-container aloha-ephemera-wrapper aloha-block aloha-block-semanticBlock"
		contenteditable="false" data-aloha-block-type="semanticBlock" id=
		"cd09bb8f-e9da-4b45-75fc-aefd7f2b969e">
			....
	</div>
	and drag and drop elements from the toolbar.
</p>
```

The bug occurs the moment that the editor tries to send a request using the html content.  For example, if you try to save the document in authoring using a PUT request ( ```http://10.11.12.13:8080/contents/60eb8549-2976-460f-8e92-c509fdcd64d7@draft.json``` )  then the html code is modified to this (notice the new end of paragraph tag that was added in the first line): 

``` html 
<p> Enter some content here. Format content,</p>
	<div class= "semantic-container aloha-ephemera-wrapper aloha-block aloha-block-semanticBlock"
		contenteditable="false" data-aloha-block-type="semanticBlock" id=
		"cd09bb8f-e9da-4b45-75fc-aefd7f2b969e">
			....
	</div> 
	and drag and drop elements from the toolbar.
<p>
````

It looks like webview is trying to break up the text string of the content into two distinct paragraph blocks.   The problem is that the second half of the string is not being properly contained within any valid html syntax.  As a result authoring cannot properly parse the content causing multiple copies of the second string to be generated.  If we get REALLY desperate we can try to catch this error in authoring but it would probably be best to try to solve it on the editor side first.

**Comment by amberwebb** [comment]
@rich-hart Text that is not contained in an HTML element IS valid HTML. You can go to the w3c validator and test that.

Part of the problem, and maybe all of it but I'm not sure yet, is that a div tag cannot semantically be contained inside a p tag.

**Comment by pumazi** [comment]
Ok, here is the solution. We'll change cnx-epub to maintain and store its content wrapped in the html and body tag. (Note, this is something archive already has in it's content response. So if anything it just helps to align the output.) This means that any thing in the body of the content will be preserved "as is," because cnx-epub won't try to extract/inject the loose nodes from/to a wrapping tag.

(This should hopefully address Connexions/cnx-epub#42 in the process.)

**Comment by rich-hart** [comment]
@amberwebb I guess your right that it is valid.  What I meant to say is that the second string looks like its supposed to be inside the \<p\> tag. So the modified HTML being sent during the authoring request will look like. 

```html
<p> Enter some content here. Format content,</p>
    <div class= "semantic-container aloha-ephemera-wrapper aloha-block aloha-block-semanticBlock"
        contenteditable="false" data-aloha-block-type="semanticBlock" id=
        "cd09bb8f-e9da-4b45-75fc-aefd7f2b969e">
            ....
    </div> 
 <p> and drag and drop elements from the toolbar. </p>
```

**Comment by edwoodward** [comment]
This is fixed on dev
