### ISSUE TITLE
Editor commenting out Processing Instructions

### ISSUE THREAD

**Issue by amberwebb** [Connexions/webview#953]
1. Derive /contents/031da8d3-b525-429c-80cf-6c8ed997733a@8.32:2/College_Physics
2. Save the page without making any changes in the editor. View the draft json and the processing instructions are included in proper format.
3. Now make a change to the text in the editor and save. View the draft json again. The processing instructions are commented out.

**Comment by pumazi** [comment]
@amberwebb I saw your messages in sprint chat. At this point, I'm also thinking authoring (or specifically cnx-epub) may be commenting them.

I'll do a test on pushing html through lxml (the python xml library). If you recall, I wasn't certain the html was getting verified in authoring. It turns out it is. What I didn't know is that it is running it through the html processor, rather than the xml processor. So, the proc-instr my be getting commented in authoring.

**Comment by amberwebb** [comment]
@pumazi Thanks for checking. It's definitely not the editor like I originally thought.

**Comment by amberwebb** [comment]
Closing this because it is not the editor, but the browser that is commenting out the processing instructions.
